#define GENERATOR_OUTA_DDR       DDRB
#define GENERATOR_OUTA_PORT      PORTB
#define GENERATOR_OUTA_PIN       PORTB3

#define GENERATOR_OUTB_DDR       DDRB
#define GENERATOR_OUTB_PORT      PORTB
#define GENERATOR_OUTB_PIN       PORTB1

#define GENERATOR_OUTC_DDR       DDRB
#define GENERATOR_OUTC_PORT      PORTB
#define GENERATOR_OUTC_PIN       PORTB0

#define GENERATOR_RATE_A_CONTROL 2
#define GENERATOR_RATE_B_CONTROL 1
#define GENERATOR_RATE_C_CONTROL 0
